version: "3"
services:
  web:
    container_name: mcberank-web
    image: mcberank/mcberank
    ports:
      - 3500:3500
    depends_on:
      - mongodb
      - influxdb
    environment:
      - MCBERANK_MONGODB_HOST=mongodb:27017
      - MCBERANK_INFLUXDB_HOST=influxdb:8086
      # This variables must be SECRET.
      # Save your private username and password into .env file.
      # If you are not sure what to do, see .env-example
      - MCBERANK_MONGODB_USERNAME=${MONGODB_USERNAME}
      - MCBERANK_MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MCBERANK_INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - MCBERANK_INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

  mongodb:
    container_name: mcberank-mongodb
    image: mongo
    volumes:
      - $PWD/data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  influxdb:
    container_name: mcberank-influxdb
    image: influxdb
    volumes:
      - $PWD/data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
